- id: notifylivingroomhumid
  alias: '[Notify] Living Room Humidity'
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_humidity
    above: 70
  action:
  - service: notify.ios_jans_iphone
    data:
      title: Wohnzimmer
      message: 'Luftfeuchtigkeit: {{ states.sensor.living_room_humidity.state }} %'
- id: notifykitchenhumid
  alias: '[Notify] Kitchen Humidity'
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_humidity
    above: 70
  action:
  - service: notify.ios_jans_iphone
    data:
      title: Küche
      message: 'Luftfeuchtigkeit: {{ states.sensor.kitchen_humidity.state }} %'
- id: notifybedroomhumid
  alias: '[Notify] Bedroom Humidity'
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_humi_stats_mean
    above: 70
  action:
  - service: notify.ios_jans_iphone
    data:
      title: Schlafzimmer
      message: 'Luftfeuchtigkeit: {{ states.sensor.bedroom_humidity.state }} %'
- id: notifybathroomhumid
  alias: '[Notify] Bathroom Humidity'
  trigger:
    platform: numeric_state
    entity_id: sensor.bathroom_humidity
    above: 70
  action:
  - service: notify.ios_jans_iphone
    data:
      title: Badezimmer
      message: 'Luftfeuchtigkeit: {{ states.sensor.bathroom_humidity.state }} %'
- id: leavinghome
  alias: Leaving Home
  trigger:
    platform: state
    entity_id: group.presence
    from: home
    to: not_home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.all_off
- id: bedroomtimer
  alias: 15min Bedroom timer
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: light.trad_bedroom_ceiling
    to: 'on'
  condition:
    condition: time
    after: 08:00:00
  action:
    service: script.turn_on
    entity_id: script.timed_lamp
- id: aquariumoff
  alias: Aquarium off
  trigger:
    platform: time
    at: '20:15:00'
  action:
    service: light.turn_off
    entity_id: light.aquarium_sunlight
    data:
      transition: 10
- id: aquariumon
  alias: Aquarium on
  trigger:
    platform: time
    at: 08:15:00
  action:
    service: light.turn_on
    entity_id: light.aquarium_sunlight
    data:
      transition: 600
- id: disable_beamer_protection
  alias: Turn off beamer protection flag after 30 minutes
  trigger:
    platform: state
    entity_id: input_boolean.disable_beamer_shutdown
    to: 'on'
  action:
  - delay:
      minutes: 30
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.disable_beamer_shutdown
- id: toggle_girlanden_light
  alias: Taster-Einzelklick für Girlanden
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001bc8edc
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.regalgirlande
- id: toggle_vitrinen_light
  alias: Taster-Doppelklick für Vitrinenlicht
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001bc8edc
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.vitrinen
- id: toggle_balcony_light
  alias: Taster-Halteklick für Balkongirlande
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001bc8edc
      click_type: hold
  action:
    service: light.toggle
    data:
      entity_id: light.onoff_plug_1
- id: toggle_bedroom_light
  alias: Taster-Halteklick für Schlafzimmerlicht
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001f35477
      click_type: hold
  action:
    service: light.toggle
    data:
      entity_id: light.huebedroomceiling
- id: toggle_bedroom_nightlight
  alias: Taster-Singleclick für Nachttischlampen
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001f35477
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.nachttischlampen
- id: toggle_bedroom_switch_all_off
  alias: Taster-Halteklick für Schlaftaster AllOff
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001f35477
      click_type: double
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
  - service: light.turn_off
    data:
      entity_id: light.bedroom_group
- id: notify_ups_offline
  alias: '[Notify] UPS Status changed'
  trigger:
  - entity_id: sensor.ups_status
    platform: state
  condition: []
  action:
  - service: notify.jan
    data_template:
      message: >
        UPS status changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

      title: "\U0001F50C⚡️ *Uninterruptable Power Alert*"

- id: notify_open_windows
  alias: '[Notify] Open windows in summer'
  trigger:
  - above: -0.5
    entity_id: sensor.temp_in_out_delta
    platform: numeric_state
  condition:
  - below: '0'
    condition: numeric_state
    entity_id: sensor.temp_statistics_outdoors_mean
    value_template: '{{ float(state.attributes.average_change) }}'
  - above: '18'
    condition: numeric_state
    entity_id: sensor.temp_statistics_outdoors_mean
  action:
  - data:
      message: 'Es ist draußen nun kühler als in der Wohnung ({{ states.sensor.temp_statistics_indoors_mean.state
        | float }} °C).

        '
      title: "\U0001F3E0\U0001F646 *Öffnet die Fenster!*"
    service: notify.homegroup
- id: notify_close_windows
  alias: '[Notify] Close windows in summer'
  trigger:
  - below: '0.5'
    entity_id: sensor.temp_in_out_delta
    platform: numeric_state
  condition:
  - above: '0'
    condition: numeric_state
    entity_id: sensor.temp_statistics_outdoors_mean
    value_template: '{{ float(state.attributes.average_change) }}'
  - above: '10'
    condition: numeric_state
    entity_id: sensor.temp_statistics_outdoors_mean
  action:
  - data:
      message: 'Es wird draußen nun wärmer als in der Wohnung ({{ states.sensor.temp_statistics_indoors_mean.state
        | float }} °C).

        '
      title: "\U0001F3E0\U0001F645 *Schließt die Fenster!*"
    service: notify.homegroup
