homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Berlin
  # Include customizations
  customize: !include customize.yaml


# Enables the Web Frontend
frontend:


# Enable API password
http:
  api_password: !secret http_password
  server_host: 127.0.0.1
  use_x_forwarded_for: true
  base_url: homeassistant

config:


# Discover some devices automatically
#discovery:


# Run MQTT for microcontroller-based IoT devices
mqtt:

zwave:
  device_config: !include zwave_device_config.yaml
  usb_path: /dev/ttyUSB0


# Tracking state changes over time, exclude some useless entities
history:
  exclude:
    entities:
      - sensor.time
      - group.weather
      - group.connectivity
      - group.bathroom
      - group.all_automations
      - group.outside
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - input_select
      - automation
      - updater
      - http
      - persistent_notification
      - script
      - group


# Record all data in external database (currently MariaDB)
recorder:
    db_url: !secret db_url


# View all events in a logbook, and exclude some useless info
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - group


# Track the sun
sun:


# Include pilight for 433MHz-based lights
pilight:
  host: 10.10.4.184
  port: 5000

binary_sensor: !include sensor_binary.yml

tradfri:
  host: 10.10.4.36
  api_key: !secret tradfri_apikey 

# Include hub-based light platforms
  # - platform: osramlightify
  #   host: 10.10.4.40

# Include network media platforms
apple_tv:
  - name: Apple TV
    host: 10.10.4.7
    login_id: !secret appletv_loginid
    start_off: on

# Device tracking
device_tracker:
  - platform: unifi
    host: 10.10.9.8
    site_id: default
    username: !secret unifi_username
    password: !secret unifi_password
    track_new_devices: false
    verify_ssl: false

ios:



# Include other config files
light: !include light.yaml
group: !include groups.yaml
scene: !include scene.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
script: !include_dir_named script
automation: !include_dir_merge_list automation
