homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Berlin
  # Include customizations
  customize: !include customize.yaml


# Enables the Web Frontend
frontend:


# Enable API password
http:
  api_password: !secret http_password


# Discover some devices automatically
#discovery:


# Run MQTT for microcontroller-based IoT devices
mqtt:


# Tracking state changes over time, exclude some useless entities
history:
  exclude:
    entities:
      - sensor.time
      - group.weather
      - group.connectivity
      - group.bathroom
      - group.all_automations
      - group.outside
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - input_select
      - automation
      - updater
      - http
      - persistent_notification
      - script
      - group
      - sonarr


# Record all data in external database (currently MariaDB)
recorder:
    db_url: !secret db_url


# View all events in a logbook, and exclude some useless info
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - group


# Track the sun
sun:


# Include pilight for 433MHz-based lights
pilight:
  host: 10.10.4.184
  port: 5000


# Include hub-based light platforms
light:
  platform: hue
  host: 10.10.4.99


# Include other config files
group: !include group.yaml
scene: !include scene.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
script: !include_dir_named script
automation: !include_dir_merge_list automation
input_select: !include input_select.yaml
