homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Berlin
  # Include customizations
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zone 2:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_lon
  radius: 250

frontend:
  themes:
    bluegrey:
      primary-color: '#7397A7'
    darkblue:
      primary-color: '#05668D'

http:
  api_password: !secret http_password
  server_host: 10.10.9.7
  server_port: 8123
  use_x_forwarded_for: true
  base_url: !secret http_base_url

# Notify about pending updates
updater:
  include_used_components: true

config:

# Run MQTT for microcontroller-based IoT devices
mqtt:
  broker: 10.10.9.7
  port: 1883
  username: homeassistant
  password: !secret http_password

# Tracking state changes over time, exclude some useless entities
history: !include history.yaml

# Record all data in external database (currently MariaDB)
recorder:
  db_url: !secret db_url
  purge_interval: 0

# View all events in a logbook, and exclude some useless info
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - group

logger:
  default: warn

sun:

tradfri:
  host: 10.10.4.36
  allow_tradfri_groups: false

hue:
  bridges:
    - host: 10.10.4.37
      allow_hue_groups: false

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key

ios:
  push:
    categories:
      - name: Notification
        identifier: 'notification'
        actions:
          - identifier: 'dismiss'
            title: 'Okay'
            behavior: 'default'
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_group_id
      - !secret telegram_jan_id

notify:
  - name: homegroup
    platform: telegram
    chat_id: !secret telegram_group_id
  - name: jan
    platform: telegram
    chat_id: !secret telegram_jan_id
  - name: all_ios_devices
    platform: group
    services:
      - service: ios_jans_iphone
      # - service: ios_iphone_two

apcupsd:
binary_sensor:
  - platform: apcupsd

  - platform: digital_ocean
    droplets:
      - box.janw.xyz

digital_ocean:
  access_token: !secret digital_ocean_api_key

# Include other config files
light: !include light.yaml
group: !include groups.yaml
scene: !include scene.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
script: !include_dir_named script
automation: !include automations.yaml
history_graph: !include history_graphs.yaml
