homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Berlin
  # Include customizations
  customize: !include customize.yaml


# Checks for available updates
#updater:
#  reporting: False

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  server_host: 127.0.0.1

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
#


# Enables support for tracking state changes over time.
history:
  exclude:
    entities:
      - sensor.yr_pressure
      - sensor.yr_cloudiness
      - sensor.time
      - group.weather
      - group.connectivity
      - group.bathroom
      - group.all_automations
      - group.outside

    domains:
      - automation
      - updater
      - http
      - persistent_notification

recorder:


# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.time
    domains:
      - group

# Track the sun
sun:

device_tracker:
  - platform: locative
    track_new_devices: False

#  - platform: unifi
#    username: !secret unifi_username
#    password: !secret unifi_password
#    host: 10.10.9.8


pilight:
  host: 10.10.5.132
  port: 5000
  whitelist:  # optional
    protocol:
      - brennenstuhl


light:
  platform: hue
  host: 10.10.4.99


# Include other config files
group: !include group.yaml
scene: !include scene.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
script: !include_dir_named script
automation: !include_dir_merge_list automation
media_player: !include media_player.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
