homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Berlin
  # Include customizations
  customize: !include customize.yaml

  customize_glob:
    "device_tracker.esp_*":
      icon: mdi:bug
    "device_tracker.rpi_*":
      icon: mdi:raspberrypi
    "light.Hue*":
      hidden: true
      homebridge_hidden: true
    "sensor.*_moisture":
      icon: mdi:cup-water
    "light.trad_*":
      homebridge_hidden: true
    "device_tracker.*":
      homebridge_hidden: true
    "sensor.dark_sky*":
      homebridge_hidden: true
    "sensor.feinstaub*":
      homebridge_hidden: true


zone 2:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_lon
  radius: 250


# Enables the Web Frontend
frontend:

# Enable API password
http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  base_url: homeassistant.whaus.xyz

# Notify about pending updates
updater:
  include_used_components: true

# Enable the web-UI config editor
config:

# Run MQTT for microcontroller-based IoT devices
mqtt:
  broker: 127.0.0.1
  port: 1883
  username: homeassistant
  password: !secret http_password


# Tracking state changes over time, exclude some useless entities
history:
  exclude:
    entities:
      - sensor.time
      - group.weather
      - group.connectivity
      - group.bathroom
      - group.all_automations
      - group.outside
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
      - switch.hallway_fluxing
      - light.huekueche
      - light.hueflur
      - light.huearbeitszimmer
      - light.hueaquarium
      - light.cesstisch
      - light.bcouchtisch
      - light.aalle_lampen
      - light.dwohnzimmer

    domains:
      - input_select
      - automation
      - updater
      - http
      - persistent_notification
      - script
      - group
      - scene


# Record all data in external database (currently MariaDB)
recorder:
    db_url: !secret db_url


# View all events in a logbook, and exclude some useless info
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - group


# Track the sun
sun:


tradfri:
  host: 10.10.4.36

# alexa:

# Device tracking
device_tracker:
  - platform: unifi
    host: 10.10.9.8
    site_id: default
    username: !secret unifi_username
    password: !secret unifi_password
    track_new_devices: false
    verify_ssl: false

ios:
  push:
    categories:
      - name: Notification
        identifier: 'notification'
        actions:
          - identifier: 'dismiss'
            title: 'Okay'
            behavior: 'default'


# Include other config files
light: !include light.yaml
group: !include groups.yaml
scene: !include scene.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
script: !include_dir_named script
intent_script: !include alexa_intents.yaml
automation: !include automations.yaml

