homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 5
  unit_system: metric
  time_zone: Europe/Berlin
  # Include customizations
  customize: !include customize.yaml


# Enables the Web Frontend
frontend:


# Enable API password
http:
  api_password: !secret http_password

config:


# Discover some devices automatically
#discovery:


# Run MQTT for microcontroller-based IoT devices
mqtt:

zwave:
  usb_path: /dev/ttyUSB0


# Tracking state changes over time, exclude some useless entities
history:
  exclude:
    entities:
      - sensor.time
      - group.weather
      - group.connectivity
      - group.bathroom
      - group.all_automations
      - group.outside
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - input_select
      - automation
      - updater
      - http
      - persistent_notification
      - script
      - group
      - sonarr


# Record all data in external database (currently MariaDB)
recorder:
    db_url: !secret db_url


# View all events in a logbook, and exclude some useless info
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_pressure
      - sensor.dark_sky_cloud_coverage
    domains:
      - group


# Track the sun
sun:


# Include pilight for 433MHz-based lights
pilight:
  host: 10.10.5.105
  port: 5000


# Include hub-based light platforms
light:
  - platform: hue
    host: 10.10.4.99
  - platform: osramlightify
    host: 10.10.4.40

  - platform: mqtt
    name: "Office Light RGB"
    state_topic: "office/rgb1/light/status"
    command_topic: "office/rgb1/light/switch"
    brightness_state_topic: "office/rgb1/brightness/status"
    brightness_command_topic: "office/rgb1/brightness/set"
    rgb_state_topic: "office/rgb1/rgb/status"
    rgb_command_topic: "office/rgb1/rgb/set"
    state_value_template: "{{ value_json.state }}"
    brightness_value_template: "{{ value_json.brightness }}"
    rgb_value_template: "{{ value_json.rgb | join(',') }}"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false



# Include network media platforms
media_player:
  - platform: apple_tv
    host: 10.10.5.39
    login_id: !secret appletv_loginid


# Include other config files
group: !include group.yaml
scene: !include scene.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
script: !include_dir_named script
automation: !include_dir_merge_list automation
input_select: !include input_select.yaml
