# Switches (mostly based on 433MHz/Pilight)

- platform: pilight
  switches:

    Curtain Balls:
      on_code:
        protocol: brennenstuhl
        systemcode: 31
        unitcode: 2
        'on': 1
      off_code:
        protocol: brennenstuhl
        systemcode: 31
        unitcode: 2
        'off': 1

    Kitchen Stereo:
      on_code:
        protocol: brennenstuhl
        systemcode: 30
        unitcode: 4
        'on': 1
      off_code:
        protocol: brennenstuhl
        systemcode: 30
        unitcode: 4
        'off': 1

    Bedroom Stereo:
      on_code:
        protocol: brennenstuhl
        systemcode: 31
        unitcode: 5
        'on': 1
      off_code:
        protocol: brennenstuhl
        systemcode: 31
        unitcode: 5
        'off': 1

    Star Lights:
      on_code:
          protocol: kaku_switch
          id: 64048982
          unit: 15
          state: on
          'on': 1
      off_code:
          protocol: kaku_switch
          id: 64048982
          unit: 15
          state: off
          'off': 1

    Christmas Star:
      on_code:
          protocol: kaku_switch
          id: 64048982
          unit: 14
          state: on
          'on': 1
      off_code:
          protocol: kaku_switch
          id: 64048982
          unit: 14
          state: off
          'off': 1


