# Time-based automations

- alias: '15min Bedroom timer'
  trigger:
    platform: state
    entity_id: light.trad_bedroom_ceiling
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.timed_lamp

